name: CI Build

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build containers
        run: docker compose build

      - name: Compose up containers
        run: docker compose up -d

      - name: Test API
        run: curl http://localhost:3000/api/
